version: '3.7'
services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        networks:
            - webapp
            - database
        depends_on:
            - postgres_db
        restart: always
        env_file:
            - ./server/.production.env
        # command: ['./wait-for-it.sh', 'postgres_db:5432', '--', 'node', 'main.js']
        command: ['./check.sh']

    client:
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile
        networks:
            - webapp
        ports:
            - 80:80
        restart: always

    postgres_db:
        container_name: postgres_db
        image: postgres
        networks:
            - database
        env_file:
            - ./server/.production.env
        volumes:
            - ./server/database/data/prod:/var/lib/postgresql/data/
        restart: always

networks:
    webapp:
        driver: bridge
    database:
        driver: bridge